### ISSUE TITLE
File Not Found: data/hyp.scratch.yaml

### ISSUE THREAD

**Issue by robmarkcole** [johnolafenwa/deepstack-trainer#1]
Attempting to train with [Firenet](https://github.com/OlafenwaMoses/FireNET) (yolo3 format I believe):
```
!wget https://github.com/OlafenwaMoses/FireNET/releases/download/v1.0/fire-dataset.zip -q
!unzip fire-dataset.zip
!python3 train.py --dataset-path "/content/deepstack-trainer/fire-dataset" --model yolov5s --batch-size 32 --classes "fire"
```

I get error:
```
Traceback (most recent call last):
  File "train.py", line 496, in <module>
    opt.cfg, opt.hyp = check_file(opt.cfg), check_file(opt.hyp)  # check files
  File "/content/deepstack-trainer/utils/general.py", line 70, in check_file
    assert len(files), 'File Not Found: %s' % file  # assert file was found
AssertionError: File Not Found: data/hyp.scratch.yaml
```

**Comment by johnolafenwa** [comment]
Hi @robmarkcole , please pull the latest update to the repo. This issue has been fixed

**Comment by robmarkcole** [comment]
fixed
